CREATE TABLE [ShipMgmt_Crewing].[tCrewServiceRecords](

	[Service Record ID] [varchar](20) NOT NULL,
	[Crew ID] [varchar](20) NULL,
	[Rank ID] [varchar](20) NULL,
	[Rank] [varchar](200) NULL,
	[Status ID] [varchar](20) NULL,
	[Status] [varchar](60) NULL,
	[Sign Off Reason ID] [varchar](20) NULL,
	[Sign Off Reason] [varchar](200) NULL,
	[Start Date] [DateTime] NULL,
	[End Date] [DateTime] NULL,
	[Sea Days] [int] NULL,
	[Months Onboard] [int] NULL,
	[Load Port ID] [varchar](20) NULL,
	[Disport ID] [varchar](20) NULL,
	[Service Cancelled] [bit] NULL,
	[Vessel ID] [varchar](20) NULL,
	[Active Status] [bit] NULL,
	[Berth ID] [varchar](20) NULL,
	[Reliever Service Record ID] [varchar](20) NULL,
	[Previous Experience] [bit] NULL,
	[Service Record UpdatedOn] [Datetime] NULL,
	[Service Record UpdatedBy ID] [varchar](20) NULL,
	[Service Record Updated By] [varchar](200) NULL,
	[Rank ID Budgeted] [varchar](20) NULL,
	[Rank Budgeted] [varchar](200) NULL,
	[Planning Status ID] [varchar](20) NULL,
	[Planning Status] [varchar](60) NULL,
	[Service Active Status ID] [int] NULL,
	[Service Active Status] [varchar](60) NULL,
	[Lineup ID Joiner] [varchar](20) NULL,
	[Lineup ID Leaver] [varchar](20) NULL,
	[Service Contract Length Unit] [varchar](12) NULL,
	[Service Contract Length Description] [varchar](60) NULL,
	[Service Vessel Management ID] [varchar](20) NULL,
	[Rank Changed Onboard] [bit] NULL,
	[Mobilisation Accepted By ID]  [varchar](20) NULL,
	[Mobilisation Accepted By] [varchar](200) NULL,
	[Mobilisation Accepted On] [datetime] NULL,
	[Crew Estimated Readiness Date] [datetime] NULL,
	[Crew Extension Reason ID] [bit] NULL,
	[Crew Extension Reason] [varchar](200) NULL,
	[Crew Extended By ID] [varchar](20) NULL,
	[Crew Extended By] [varchar](200) NULL,
	[Crew Extended On] [datetime] NULL,
	[Extension Agreed by Seafarer] [bit] NULL,
	[Extension Valid Until] [datetime] NULL,
	[Extension Approved]  [bit] NULL,
	[ChangeIdentifier] [int] NOT NULL,

 CONSTRAINT [PK__CrewServiceRecords__ServiceRecordID] PRIMARY KEY CLUSTERED 
(
	[Service Record ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO