CREATE TABLE [ShipMgmt_Crewing].[tCrewCompliance](
	[Run Day] [datetime] NOT NULL,
	[Crew ID] [varchar] (20) NULL,
	[Vessel ID] [varchar] (20) NULL,
	[Vessel Mgmt ID] [varchar] (20) NULL,
	[Rank ID] [varchar] (20) NULL,
	[Rank Sequence] [varchar] (20) NULL,
	[Crew Status] [varchar] (50) NULL,
	[Start Date] [datetime] NULL,
	[End Date] [datetime] NULL,
	[Document Number] [varchar] (1000) NULL,
	[Document ID] [varchar] (20) NULL,
	[Document Country ID] [varchar] (20) NULL,
	[Document Issued Date] [date] NULL,
	[Document Expiry Date] [date] NULL,
	[Document Description] [varchar] (2000) NULL,
	[Document General Name] [varchar] (2000) NULL,
	[Sign On Status] [varchar] (50) NULL,
	[Sign Off Status] [varchar] (50) NULL,
	[Note] [varchar] (2000) NULL,
	[Grace Period] [varchar] (50) NULL,
	[Sign On Note] [varchar] (2000) NULL,
	[Sign Off Note] [varchar] (2000) NULL,
	[Template Name] [varchar] (1000) NULL,
	[Template is Core] [bit] NULL,
	[Document Requirement Short Code] [varchar] (50) NULL,
	[Document Requirement] [varchar] (1000) NULL,
	[Last Date of Grace Period] [date] NULL,
	[Document Non Compliant] [bit] NULL,
	[Document Compliance] [varchar] (50) NULL,
	[Template ID] [varchar] (20) NULL,
	[Company To Exclude] [varchar] (50) NULL,
	[Template Requirement] [varchar] (50) NULL,
	[Effective Start Date] [datetime] NULL,
	[Reporting Start Date] [datetime] NULL,
	[Training Type] [varchar] (50) NULL,
	[CPI Report] [varchar] (50) NULL,
	[Exclusion Start Date] [datetime] NULL,
	[Exclusion End Date] [datetime] NULL,
	[Exclusion Category] [varchar] (50) NULL,
	[Remarks] [varchar] (2000) NULL,
	[Is Flag State] [varchar] (20) NULL,
	[Requirement Type] [varchar] (20) NULL,
	[Is Default Template] [varchar] (20) NULL,
	[Document Group Type] [varchar] (50) NULL,
	[Sign On 14 Days] [varchar] (20) NULL,
	[Document Missing] [bit] NULL,
	[Document Expired at Sign Off] [bit] NULL,
	[Document Expired] [bit] NULL,
	[Grace Period Allowance] [varchar] (20) NULL,
	[Document Status] [varchar] (20) NULL,
	[Note Short Code] [varchar] (2000) NULL,
	[Expiry Status] [varchar] (50) NULL,
	[Days To Expire] [varchar] (100) NULL,
	[Document Missing Without Dispensation] [bit] NULL,
	[Document Expired at Sign Off Without Dispensation] [bit] NULL,
	[Document Expired WithoutDispensation] [bit] NULL,
	[Dispensation Status] [varchar] (100) NULL,
	[Dispensation] [varchar] (20) NULL,
	[Document Non Compliance Ignoring Dispensation] [bit] NULL,
	[Document Compliance Ignoring Dispensation] [varchar] (20) NULL,
	[Non Compliant Grace] [bit] NULL,
	[Grace Period Exists] [bit] NULL,
	[Grace Period Missing] [bit] NULL,
	[Grace Period Within Grace Period] [bit] NULL,
	[Grace Period Expired at Sign Off] [bit] NULL,
	[Grace Period Document Status] [varchar] (50) NULL,
	[Grace Include Dispensation Compliance] [varchar] (50) NULL,
	[Grace Dispensation Compliance] [varchar] (50) NULL,
	[Non Compliant Grace Dispensation] [bit] NULL,
	[Grace Period Dispensation Document Status] [varchar] (50) NULL,
	[Grace Period Dispensation Exists] [bit] NULL,
	[Grace Period Dispensation Missing] [bit] NULL,
	[OTG Code Grace] [varchar] (50) NULL,
	[Course Color Category] [varchar] (50) NULL,
	[Row ID] [varchar] (2000) NOT NULL,

CONSTRAINT [PK__CrewCompliance__RowID] PRIMARY KEY CLUSTERED 
(
	[Row ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO