use shipsure
go

SELECT
			INVOICEHDR.COY_ID,
			INVOICEHDR.INH_ID,
			INVOICEHDR.INH_PAYRUNNO,
			INVOICEHDR.INH_TotalCurr,
			INVOICEHDR.CUR_ID,
			INVOICEHDR.INH_TotalBase as FuntionalAmount,
			INVOICEHDR.INH_DatePaid,
			USERID.USR_DisplayName,
			INVOICEHDR.INH_DatePaidAct as IAL_UpdatedOn
		FROM
			INVOICEHDR
			LEFT JOIN INVAUDITLOG ON INVOICEHDR.INH_Voucher = INVAUDITLOG.INH_Voucher AND INVOICEHDR.COY_ID = INVAUDITLOG.COY_ID AND INVAUDITLOG.IAT_ID = 'GLAS00000021'
			LEFT JOIN USERID ON INVAUDITLOG.IAL_UpdatedBy = USERID.USR_ID
		WHERE 
			/*INVOICEHDR.COY_ID = @sCoyId AND*/ INVOICEHDR.INH_Origin = 'R' AND INVOICEHDR.INH_Status = 30 AND cast(INVOICEHDR.INH_DatePaidAct as date)
			BETWEEN '2024-05-01' and '2024-05-31'
			/*BETWEEN '2024-03-01' AND GETDATE()*/
			AND INVOICEHDR.COY_ID = 'CHEN'
			
			/*IN ('CHEN',
'ITMD',
'ITML',
'SMSG',
'VSA',
'BOS',
'VOF',
'VCY',
'DSMA',
'DSMB',
'VFR',
'GER',
'HSSG',
'NRSG',
'GLW',
'MSTN',
'VLU',
'VMIN',
'VSOL',
'ITMB',
'ITMM',
'VSG',
'VML',
'NOR',
'BIPL',
'BSIN',
'CMPL',
'IMTS',
'IMT',
'IND',
'VSI',
'KES',
'MED',
'NSM',
'POMI',
'VABU',
'VGGS',
'VGP',
'VSO',
'FPIM',
'VIOM',
'ISTA',
'VMN',
'ROM',
'CCTC',
'VSTI',
'MTS',
'ADA',
'MARC',
'SSCM',
'VSCR',
'VSPA',
'VCEX',
'VPSS',
'VMSL',
'VVA')*/
		ORDER BY
			INVOICEHDR.INH_DatePaid desc