--tCrewAppDocuments

SELECT
	app.RowID as [Row ID],
	app.InsertedOn as [Inserted On],
	app.crw_id as  [Crew ID],
	app.rnk_id as [Rank ID],
	app.[Rank],
	app.[RankCategory] as [Rank Category],
	app.[Nationality],
	app.[MOBILISATIONOFFICE_ID] as [Mobilisation Office ID],
	app.SMO_ID as [Technical Office ID],
	app.[SMO] as [Technical Office],
	app.Client_ID as [Client ID],
	app.[Client],
	app.PlanningCell_iD [Planning Cell ID],
	app.[PlanningCell] as [Planning Cell],
	app.MobilisationCell_ID as [Mobilisation Cell ID],
	app.[MobilisationCell] as [Mobilisation Cell],
	app.CurrentStatus as [Current Status],
	app.VESSEL_ID_FINAL as [Vessel ID Final],
	app.VESSEL_NAME_FINAL as [Vessel Name Final],
	app.VESSEL_TYPE_FINAL as [Vessel Type Final],
	app.SECTOR_FINAL as [Sector Final],
	app.Management_type_FINAL as [Management Type Final],
	app.AttachementID as [Attachment ID],
	app.UploadedBy as [Uploaded By ID],
	ud.USR_DisplayName as [Uploaded By],
	app.UploadedOn as [Uploaded On],
	app.UploadedbyUnit as [Uploaded by Unit],
	app.Description as [Document Description],
	app.FileName as [File Name],
	app.documentID as [Document ID],
	app.Name as [Document Name],
	app.Comments,
	app.Status [Document Status],
	app.crw_employmenttype [Crew Employment Type ID],
	ccn.ccn_description as [Crew Employment Type],
	app.crd_country as [Document Issued Country ID],
	CASE WHEN DS.IN_SCOPE = 'YES' THEN 'IN SCOPE' ELSE 'OUT OF SCOPE' END AS [Document Scope],
	BINARY_CHECKSUM(
		app.InsertedOn,
		app.crw_id,
		app.rnk_id,
		app.[Rank],
		app.[RankCategory],
		app.[Nationality],
		app.[MOBILISATIONOFFICE_ID],
		app.SMO_ID,
		app.[SMO],
		app.Client_ID,
		app.[Client],
		app.PlanningCell_iD,
		app.[PlanningCell],
		app.MobilisationCell_ID,
		app.[MobilisationCell],
		app.CurrentStatus,
		app.VESSEL_ID_FINAL,
		app.VESSEL_NAME_FINAL,
		app.VESSEL_TYPE_FINAL,
		app.SECTOR_FINAL,
		app.Management_type_FINAL,
		app.AttachementID,
		app.UploadedBy,
		ud.USR_DisplayName,
		app.UploadedOn,
		app.UploadedbyUnit,
		app.Description,
		app.FileName,
		app.documentID,
		app.Name,
		app.Comments,
		app.Status,
		app.crw_employmenttype,
		app.crd_country
		) [ChangeIdentifier]


FROM aggregates..crew_appdocuments app
LEFT JOIN shipsure..USERID (NOLOCK) UD ON UD.USR_ID = app.UploadedBy
LEFT JOIN Aggregates..CRWMobileDocumentUploadScope DS ON DS.Doc_Desc = App.[Name]
LEFT JOIN Shipsure..CRWSrvContractType ccn ON ccn.CCN_ID = app.CRW_EmploymentType
WHERE cast(app.insertedon as date) >= DATEADD(yyyy,-1,getdate())