--tCrewComplianceTrends

SELECT
	RowId as [Row ID],
	RecInsertedOn as [Record Inserted On],
	Crw_ID as [Crew ID],
	PCN as [PCN],
	rnk_id as [Rank ID],
	MobilisationCellID [Mobilisation Cell ID],
	MobilisationOfficeID [Mobilisation Office ID],
	PlanningCellID [Planning Cell ID],
	PlanningOfficeID [Planning Office ID],
	TPA as [Third Party Agency],
	CrewStatus [Crew Status],
	Set_id as [Service Record ID],
	VMD_ID [Vessel Mgmt ID],
	Vessel_Id [Vessel ID],
	Vessel [Vessel],
	SigOnL14Days [Signed On Last 14 Days],
	CPIReportVessel [Vessel In Scope CPI],
	DefaultTemplate [Default Template],
	TrainingType [Training Type],
	IsCore [Is Core],
	TemplateRequirement [Template Requirement],
	IsFlag [Is Flag Document],
	StatutoryDocuments [Statutory Documents],
	StatutoryCompliantDocuments [Statutory Compliant Documents],
	StatutoryNonCompliantDocuments [Statutory Non Compliant Documents],
	TravelDocuments [Travel Documents],
	TravelCompliantDocuments [Travel Compliant Documents],
	TravelNonCompliantDocuments [Travel Non Compliant Documents],
	VMSDocuments [VMS Documents],
	VMSCompliantDocuments [VMS Compliant Documents],
	VMSNonCompliantDocuments [VMS Non Compliant Documents],
	OtherDocuments [Other Documents],
	OtherCompliantDocuments [Other Compliant Documents],
	OtherNonCompliantDocuments [Other Non Compliant Documents],
	DocumentsCount [Total Documents Count],
	CompliantDocuments [Total Compliant Documents],
	NonCompliantDocuments [Total Non Compliant Documents],
	CMPCellID [CMP Cell ID],
	CourseColourCategory [Course Color Category],
	BINARY_CHECKSUM(
		RowId,
		RecInsertedOn,
		Crw_ID,
		PCN,
		rnk_id,
		MobilisationCellID,
		MobilisationOfficeID,
		PlanningCellID,
		PlanningOfficeID,
		TPA,
		CrewStatus,
		Set_id,
		VMD_ID,
		Vessel_Id,
		Vessel,
		SigOnL14Days,
		CPIReportVessel,
		DefaultTemplate,
		TrainingType,
		IsCore,
		TemplateRequirement,
		IsFlag,
		StatutoryDocuments,
		StatutoryCompliantDocuments,
		StatutoryNonCompliantDocuments ,
		TravelDocuments,
		TravelCompliantDocuments,
		TravelNonCompliantDocuments,
		VMSDocuments,
		VMSCompliantDocuments,
		VMSNonCompliantDocuments,
		OtherDocuments,
		OtherCompliantDocuments,
		OtherNonCompliantDocuments,
		DocumentsCount,
		CompliantDocuments,
		NonCompliantDocuments,
		CMPCellID,
		CourseColourCategory
	) [ChangeIdentifier]


FROM Aggregates.[dbo].[CREW_CrewComplianceTrend_UPDATED]
WHERE Datekey >= 20230101